import { BookRecord } from "@/types/book";

export const BookRecords: BookRecord[] = [
  {
    id: "1",
    title: "클린 코드",
    author: "로버트 C. 마틴",
    publisher: "인사이트",
    publicationDate: "2013-12-24",
    totalPages: 584,
    readingStatus: "WANT_TO_READ",
    startDate: null,
    endDate: null,
    recommend: null,
    rating: null,
    review: null,
    quotes: [],
    isPublic: false,
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    title: "함께 자라기",
    author: "김창준",
    publisher: "인사이트",
    publicationDate: "2019-06-17",
    totalPages: 280,
    readingStatus: "WANT_TO_READ",
    startDate: null,
    endDate: null,
    recommend: null,
    rating: null,
    review: null,
    quotes: [],
    isPublic: false,
    createdAt: "2024-01-16T14:20:00Z",
    updatedAt: "2024-01-16T14:20:00Z",
  },
  {
    id: "3",
    title: "객체지향의 사실과 오해",
    author: "조영호",
    publisher: "위키북스",
    publicationDate: "2015-06-17",
    totalPages: 372,
    readingStatus: "WANT_TO_READ",
    startDate: null,
    endDate: null,
    recommend: null,
    rating: null,
    review: null,
    quotes: [],
    isPublic: false,
    createdAt: "2024-01-17T09:15:00Z",
    updatedAt: "2024-01-17T09:15:00Z",
  },
  {
    id: "4",
    title: "리팩토링",
    author: "마틴 파울러",
    publisher: "한빛미디어",
    publicationDate: "2010-04-12",
    totalPages: 448,
    readingStatus: "WANT_TO_READ",
    startDate: null,
    endDate: null,
    recommend: null,
    rating: null,
    review: null,
    quotes: [],
    isPublic: false,
    createdAt: "2024-01-18T16:45:00Z",
    updatedAt: "2024-01-18T16:45:00Z",
  },
  {
    id: "5",
    title: "도메인 주도 설계",
    author: "에릭 에반스",
    publisher: "위키북스",
    publicationDate: "2011-06-20",
    totalPages: 520,
    readingStatus: "WANT_TO_READ",
    startDate: null,
    endDate: null,
    recommend: null,
    rating: null,
    review: null,
    quotes: [],
    isPublic: false,
    createdAt: "2024-01-19T11:30:00Z",
    updatedAt: "2024-01-19T11:30:00Z",
  },
];
